// Generated by CoffeeScript 1.4.0
var SceneManager;

SceneManager = (function() {
  var PrivateClass, instance;

  function SceneManager() {}

  instance = null;

  PrivateClass = (function() {

    function PrivateClass() {
      this.scenes = [];
      this.index = 0;
    }

    PrivateClass.prototype.addScene = function(scene) {
      return this.scenes.push(scene);
    };

    PrivateClass.prototype.setScene = function(i) {
      return this.index = i;
    };

    PrivateClass.prototype.isEmpty = function() {
      return this.scenes.length === 0;
    };

    PrivateClass.prototype.scene = function() {
      return this.scenes[this.index];
    };

    PrivateClass.prototype.tick = function(delta, now) {
      return this.scene().tick(delta, now);
    };

    return PrivateClass;

  })();

  SceneManager.get = function() {
    return instance != null ? instance : instance = new PrivateClass();
  };

  return SceneManager;

})();
