// Generated by CoffeeScript 1.4.0
var Zombie;

Zombie = (function() {

  function Zombie() {
    var geometry, material;
    geometry = new THREE.CubeGeometry(0.3, 0.3, 0.3);
    material = new THREE.MeshPhongMaterial({
      color: new THREE.Color("gray")
    });
    this.mesh = new THREE.Mesh(geometry, material);
    this.mesh.position.set(0, geometry.height / 2, 0);
    this.mesh.receiveShadow = true;
    this.mesh.castShadow = true;
    this.speed = 2;
    this.directionX = 0;
    this.directionZ = 0;
    this.position = this.mesh.position;
  }

  Zombie.prototype.move = function(delta) {
    this.mesh.position.x += this.speed * delta * this.directionX;
    return this.mesh.position.z += this.speed * delta * this.directionZ;
  };

  return Zombie;

})();
