// Generated by CoffeeScript 1.4.0
var Zombie;

Zombie = (function() {
  var DYNAMIC_TEXTURE_SIZE;

  DYNAMIC_TEXTURE_SIZE = 128;

  function Zombie() {
    var geometry, material;
    this.dynamicTexture = new THREEx.DynamicTexture(DYNAMIC_TEXTURE_SIZE, DYNAMIC_TEXTURE_SIZE);
    this.dynamicTexture.context.font = "30px Verdana";
    geometry = new THREE.CubeGeometry(0.3, 0.3, 0.3);
    material = new THREE.MeshPhongMaterial({
      map: this.dynamicTexture.texture
    });
    this.mesh = new THREE.Mesh(geometry, material);
    this.mesh.position.set(0, geometry.height / 2, 0);
    this.mesh.receiveShadow = true;
    this.mesh.castShadow = true;
    this.speed = 2;
    this.directionX = 0;
    this.directionZ = 0;
    this.position = this.mesh.position;
    this.say(':D');
  }

  Zombie.prototype.move = function(delta) {
    this.mesh.position.x += this.speed * delta * this.directionX;
    this.mesh.position.z += this.speed * delta * this.directionZ;
    if (this.directionX !== 0 || this.directionZ !== 0) {
      return this.mesh.rotation.y += this.speed * delta * 8;
    }
  };

  Zombie.prototype.say = function(s) {
    var half;
    this.dynamicTexture.clear();
    half = DYNAMIC_TEXTURE_SIZE / 2;
    return this.dynamicTexture.drawText(s, half - s.length * 8, half, 'white');
  };

  return Zombie;

})();
