// Generated by CoffeeScript 1.4.0
var Level4,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Level4 = (function(_super) {

  __extends(Level4, _super);

  function Level4() {
    var door;
    Level4.__super__.constructor.call(this);
    this.player.say(":D");
    this.ground = new Ground();
    this.scene.add(this.ground.mesh);
    door = new Door("prize");
    door.mesh.position.set(0, 0.2, -1.5);
    this.scene.add(door.mesh);
    door = new Door("back");
    door.mesh.position.set(1.2, 0.2, 2.2);
    this.scene.add(door.mesh);
    this.addSpotlight(0, 2.5, 2);
  }

  return Level4;

})(BaseLevel);
