// Generated by CoffeeScript 1.4.0
var Level0,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Level0 = (function(_super) {

  __extends(Level0, _super);

  function Level0() {
    var door;
    Level0.__super__.constructor.call(this);
    this.player.say(":)");
    this.ground = new Ground();
    this.scene.add(this.ground.mesh);
    door = new Door("door");
    door.mesh.position.set(-1, 0.2, -2);
    this.scene.add(door.mesh);
    door = new Door("door");
    door.mesh.position.set(1, 0.2, -2);
    this.scene.add(door.mesh);
    this.addSpotlight(1, 2.5, 2);
    this.addSpotlight(-1, 2.5, 2);
  }

  Level0.prototype.tick = function(delta, amount) {
    var above;
    Level0.__super__.tick.call(this, delta, amount);
    return above = this.ground.isAboveGround(this.player);
  };

  return Level0;

})(BaseLevel);
